language: cpp
compiler: gcc
dist: trusty

before_install:
  # Make scripts executable
  - chmod +x ./scripts/*
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # OCLint
  - ./scripts/install_oclint

install:
  # Get my folder
  - my_github=${PWD##*/}
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # SFML
  - cd ..
  - wget https://www.sfml-dev.org/files/SFML-2.5.0-windows-gcc-7.3.0-mingw-32-bit.zip
  - unzip SFML-2.5.0-windows-gcc-7.3.0-mingw-32-bit.zip
  - mv SFML-2.5.0 sfml
  - cd $my_github
  - ls
  - ls ..
  - ls ../sfml
  # XRandR, else you get 'Failed to use the XRandR extension while trying to get the desktop video modes'
  - sudo apt-get install libxrandr-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # SLOCcount
  - sudo apt-get install sloccount

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # Build and run the tests
  - ./scripts/build_ci
  #- make --silent build
  - ./bin/geneak
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./scripts/do_oclint
  # SLOCcount
  - rm -rf oclint-0.10.3 oclint-0.10.3-x86_64-linux-3.13.0-74-generic.tar.gz oclint.log
  - cd ..; sloccount $my_github; cd $my_github
