language: cpp
compiler: gcc
dist: trusty

addons: 
  apt: 
    packages: 
      - libboost-all-dev

before_install:
  # Make scripts executable
  - chmod +x ./scripts/*
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # Get my folder
  - my_github=${PWD##*/}
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # SFML
  - cd ..
  - wget https://www.sfml-dev.org/files/SFML-2.5.0-linux-gcc-64-bit.tar.gz
  - tar -zxf SFML-2.5.0-linux-gcc-64-bit.tar.gz
  - ls
  - mv SFML-2.5.0 sfml
  - cd $my_github
  - ls
  - ls ..
  - ls ../sfml
  # SFML dependencies
  - sudo apt-get install libxrandr-dev
  #- sudo apt-get install libxlib-dev
  #- sudo apt-get install libudev-dev
  - sudo apt-get install libopenal-dev
  #- sudo apt-get install libflac-dev
  #- sudo apt-get install libvorbis-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # OCLint
  - ./scripts/install_oclint
  # SLOCcount
  - sudo apt-get install sloccount

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # Build and run the tests
  - ./scripts/build_ci
  #- make --silent build
  - export LD_LIBRARY_PATH=../sfml/lib && ./bin/geneak --ci
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./scripts/do_oclint
  # SLOCcount
  - rm -rf oclint-0.10.3 oclint-0.10.3-x86_64-linux-3.13.0-74-generic.tar.gz oclint.log
  - cd ..; sloccount $my_github; cd $my_github
