language: cpp
dist: bionic
compiler: gcc

before_install:
  # Make scripts executable
  - chmod +x ./scripts/*
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Get my folder
  - my_github=${PWD##*/}
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # SFML
  - sudo apt-get install libsfml-dev
  # SFML, the hard way
  #- cd ..
  #- wget https://www.sfml-dev.org/files/SFML-2.5.0-linux-gcc-64-bit.tar.gz
  #- tar -zxf SFML-2.5.0-linux-gcc-64-bit.tar.gz
  #- ls
  #- mv SFML-2.5.0 sfml
  #- cd $my_github
  #- ls
  #- ls ..
  #- ls ../sfml
#  # OpenGL
#  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
#  # SFML dependencies
#  - sudo apt-get install libxrandr-dev
#  - sudo apt-get install libxlib-dev
#  - sudo apt-get install libudev-dev
#  - sudo apt-get install libopenal-dev
#  - sudo apt-get install libflac-dev
#  - sudo apt-get install libvorbis-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # OCLint
  - ./scripts/install_oclint || true
  # SLOCcount
  - sudo apt-get install sloccount

services:
  - xvfb

script:
  # Build and run the tests, the hard way
  #- ./scripts/build_ci
  #- make --silent build
  #- export LD_LIBRARY_PATH=../sfml/lib && ./bin/geneak --ci
  # Build and run the tests, the easy way
  - cd src
  - cp resources/*.* .
  - qmake
  - make
  - ./geneak --ci
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - cd ..
  - ./scripts/do_oclint
  # SLOCcount
  - rm -rf oclint-0.10.3 oclint-0.10.3-x86_64-linux-3.13.0-74-generic.tar.gz oclint.log
  - cd ..; sloccount $my_github; cd $my_github
