#!/bin/bash
cd ../bin
g++ -c -std=c++14 -DNDEBUG -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Werror -Wno-unused-variable -fext-numeric-literals -I../src ../src/*
g++ *.o -o geneak.exe
# -IC:/sfml/include
# -LC:/sfml/lib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
