#!/bin/bash
cd ..
mkdir bin
cd bin
g++ -c -std=c++14 -DNDEBUG -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Werror -Wno-unused-variable -fext-numeric-literals -I/usr/include/SFML -I../src ../src/*
g++ *.o -o geneak -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
